---
title: "relevances"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{relevances}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(lgpr2)
```

## Data simulation

```{r}
dat <- simulate(40, 0.3, c(1, 1, 0, 0), 0.2)
df <- data.frame(cbind(dat$x, dat$y))
colnames(df)[ncol(df)] <- "y"
```

## Model

```{r}
mod <- LonModel$new(y ~ gp(x1) + gp(x2) + gp(x3) + gp(x4))
fit <- mod$fit(data = df, chains = 1)
fit$plot()
```

## Relevances


```{r}
fit$relevances()
```

## Project


```{r}
draw_inds <- c(1:60)
p1 <- fit$project(1, draw_inds = draw_inds)
p12 <- fit$project(c(1, 2), draw_inds = draw_inds)
p123 <- fit$project(c(1, 2, 3), draw_inds = draw_inds)
p1234 <- fit$project(c(1, 2, 3, 4), draw_inds = draw_inds)
```
## Search


```{r, fig.width=7, fig.height=4}
fs <- pp_forward_search(fit, NULL, 3)

plot_pp_pexp(fs)
plot_pp_elpd(fs, fit$get_loo_estimates())
```
